import * as path from 'path';
import { app, session, BrowserWindow, dialog, ipcMain, Menu } from 'electron';

import api from './api/api';
import { startEngine, stopEngine, whenEngineReady, EngineLaunchOptions } from './engine/launcher';
import { engineClient, IPC_PROTOCOL_VERSION, EngineClientFatalError } from './engine/client';
import { engineRpc } from './engine/rpc';
import {
  handleEngineCall,
  registerNotificationForwarders,
  NotificationSink,
} from './ipc/main-handlers';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// Windows on ARM64 fails to launch Electron's GPU process (error_code=18 from
// gpu_process_host.cc, followed by "GPU process isn't usable. Goodbye."). Software
// compositing alone isn't sufficient because the GPU process still spawns for
// rasterization and other features; --in-process-gpu collapses it into the main
// process so no separate child is launched. Must run before app.whenReady().
if (process.platform === 'win32' && process.arch === 'arm64') {
  app.disableHardwareAcceleration();
  app.commandLine.appendSwitch('in-process-gpu');
  app.commandLine.appendSwitch('disable-gpu-compositing');
}

/**
 * Currently visible main window, or {@code null} when the user has closed
 * every window without quitting (legitimate on macOS — the app stays
 * resident and {@code app.on('activate')} will recreate one). The
 * notification sink reads this lazily so the engine's notification fan-out
 * always targets the live window without holding a reference to a
 * destroyed one across close/reopen cycles.
 */
let currentMainWindow: BrowserWindow | null = null;

const createWindow = (): void => {
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 600,
    minWidth: 600,
    minHeight: 600,
    show: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  mainWindow.once('ready-to-show', () => {
    mainWindow.show();
  });

  mainWindow.once('closed', () => {
    if (currentMainWindow === mainWindow) {
      currentMainWindow = null;
    }
  });

  currentMainWindow = mainWindow;

  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

/**
 * Registers app-lifetime singletons that must NOT be re-registered when
 * the user closes the main window and reopens one (macOS dock-click
 * pattern). Specifically:
 *   - {@code ipcMain.handle('selectPath')} and
 *     {@code ipcMain.handle('engineCall')} — Electron's contract is that
 *     {@code ipcMain.handle} throws on duplicate registration, so binding
 *     these per-window crashed the second window-open with
 *     "Attempted to register a second handler for 'selectPath'".
 *   - {@code session.defaultSession.webRequest.onHeadersReceived} — same
 *     leak: each call appended a new listener, and on close+reopen the
 *     stale ones still fired against destroyed contexts.
 *   - The engine-notification fan-out — {@link registerNotificationForwarders}
 *     installs one listener per JSON-RPC method on {@code engineRpc}, and
 *     each one captured a {@code BrowserWindow} reference. Hooking the
 *     sink to {@link currentMainWindow} (read lazily) lets the same
 *     forwarder set survive any number of window close/reopen cycles
 *     without leaking.
 *
 * Idempotent: the {@code registered} flag short-circuits any accidental
 * second invocation.
 */
let appLifetimeRegistered = false;
let teardownNotificationForwarders: (() => void) | null = null;
function registerAppLifetimeIPC(): void {
  if (appLifetimeRegistered) {
    return;
  }
  appLifetimeRegistered = true;

  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        // Implement CSP
      },
    });
  });

  ipcMain.handle('selectPath', async (_event, options) => {
    return api.selectPath(options);
  });

  ipcMain.handle('engineCall', async (_event, method: string, params: unknown) =>
    handleEngineCall(method, params, engineRpc),
  );

  const sink: NotificationSink = {
    send: (envelope) => {
      const win = currentMainWindow;
      if (win && !win.isDestroyed()) {
        win.webContents.send('engineNotification', envelope);
      }
    },
    isClosed: () => {
      const win = currentMainWindow;
      return win === null || win.isDestroyed();
    },
  };
  teardownNotificationForwarders = registerNotificationForwarders(engineRpc, sink);
}

let appMenuSetup = false;
function setupMainMenu(): void {
  if (appMenuSetup) return;
  appMenuSetup = true;

  const appName = app.getName();

  const sendCommand = (command: string) => {
    const win = currentMainWindow;
    if (!win || win.isDestroyed()) return;
    win.webContents.send('mainMenuCommand', command);
  };

  const COMMAND_IDS: Record<string, string> = {
    newScanDefiniton: 'cmd-new-scan-definition',
    deleteScanDefiniton: 'cmd-delete-scan-definition',
    scan: 'cmd-scan',
    scanAndMerge: 'cmd-scan-and-merge',
    replaceSource: 'cmd-replace-source',
    replaceTarget: 'cmd-replace-target',
    fileAttributes: 'cmd-view-file-attributes',
    viewScan: 'cmd-view-scan',
    viewHistory: 'cmd-view-history',
    displaySettings: 'cmd-display-settings',
  };

  const scanMenu: Electron.MenuItemConstructorOptions = {
    label: 'Scan',
    submenu: [
      {
        label: MainMenuLabels.newScanDefinition,
        accelerator: 'CmdOrCtrl+N',
        click: () => sendCommand('newScanDefiniton'),
        id: COMMAND_IDS.newScanDefiniton,
      },
      {
        label: MainMenuLabels.deleteScanDefinition,
        accelerator: 'CmdOrCtrl+D',
        click: () => sendCommand('deleteScanDefiniton'),
        id: COMMAND_IDS.deleteScanDefiniton,
      },
      { type: 'separator' },
      {
        label: MainMenuLabels.scan,
        accelerator: 'CmdOrCtrl+S',
        click: () => sendCommand('scan'),
        id: COMMAND_IDS.scan,
      },
      {
        label: MainMenuLabels.scanAndMerge,
        accelerator: 'CmdOrCtrl+M',
        click: () => sendCommand('scanAndMerge'),
        id: COMMAND_IDS.scanAndMerge,
      },
    ],
  };

  const resultsMenu: Electron.MenuItemConstructorOptions = {
    label: 'Results',
    submenu: [
      {
        label: MainMenuLabels.replaceSource,
        accelerator: 'CmdOrCtrl+O',
        click: () => sendCommand('replaceSource'),
        id: COMMAND_IDS.replaceSource,
      },
      {
        label: MainMenuLabels.replaceTarget,
        accelerator: 'CmdOrCtrl+T',
        click: () => sendCommand('replaceTarget'),
        id: COMMAND_IDS.replaceTarget,
      },
      { type: 'separator' },
      {
        label: MainMenuLabels.fileAttributes,
        click: () => sendCommand('fileAttributes'),
        id: COMMAND_IDS.fileAttributes,
      },
    ],
  };

  const viewMenu: Electron.MenuItemConstructorOptions = {
    label: 'View',
    submenu: [
      { label: MainMenuLabels.viewScan, click: () => sendCommand('viewScan'), id: COMMAND_IDS.viewScan },
      { label: MainMenuLabels.viewHistory, click: () => sendCommand('viewHistory'), id: COMMAND_IDS.viewHistory },
    ],
  };

  const toolsMenu: Electron.MenuItemConstructorOptions = {
    label: 'Tools',
    submenu: [
      {
        label: MainMenuLabels.settings,
        accelerator: 'CmdOrCtrl+,',
        click: () => sendCommand('displaySettings'),
        id: COMMAND_IDS.displaySettings,
      },
    ],
  };

  // Labels and accelerators mirror the Swing UI (when present), but the
  // actual execution happens in the renderer via mainMenuCommand.
  const macAppSubmenu: Electron.MenuItemConstructorOptions[] = [
    { role: 'about' },
    { type: 'separator' },
    { role: 'quit' },
  ];

  const nonMacAppSubmenu: Electron.MenuItemConstructorOptions[] = [
    {
      label: `About ${appName}`,
      role: 'about',
    },
    { type: 'separator' },
    {
      label: `Quit ${appName}`,
      role: 'quit',
      accelerator: 'CmdOrCtrl+Q',
    },
  ];

  const template: Electron.MenuItemConstructorOptions[] = [
    {
      label: appName,
      submenu: process.platform === 'darwin' ? macAppSubmenu : nonMacAppSubmenu,
    },
    scanMenu,
    resultsMenu,
    viewMenu,
    toolsMenu,
  ];

  const menu = Menu.buildFromTemplate(template);
  Menu.setApplicationMenu(menu);

  // Default all "focused target required" actions to disabled. Renderer
  // will immediately update the enabled state over IPC.
  const setById = (id: string, enabled: boolean) => {
    const item = menu.getMenuItemById(id);
    if (item) item.enabled = enabled;
  };

  setById(COMMAND_IDS.newScanDefiniton, false);
  setById(COMMAND_IDS.deleteScanDefiniton, false);
  setById(COMMAND_IDS.scan, false);
  setById(COMMAND_IDS.scanAndMerge, false);
  setById(COMMAND_IDS.replaceSource, false);
  setById(COMMAND_IDS.replaceTarget, false);
  setById(COMMAND_IDS.fileAttributes, false);

  ipcMain.on('mainMenuState', (_event, state: import('./main-menu/mainMenuState').MainMenuStateWire) => {
    if (!state) return;

    setById(COMMAND_IDS.newScanDefiniton, state.canNewScanDefiniton);
    setById(COMMAND_IDS.deleteScanDefiniton, state.canDeleteScanDefiniton);
    setById(COMMAND_IDS.scan, state.canScan);
    setById(COMMAND_IDS.scanAndMerge, state.canScanAndMerge);

    setById(COMMAND_IDS.replaceSource, state.canReplaceSource);
    setById(COMMAND_IDS.replaceTarget, state.canReplaceTarget);
    setById(COMMAND_IDS.fileAttributes, state.canSourceAttributes || state.canTargetAttributes);

    // Navigation + settings
    setById(COMMAND_IDS.viewScan, state.canViewScan);
    setById(COMMAND_IDS.viewHistory, state.canViewHistory);
    setById(COMMAND_IDS.displaySettings, state.canDisplaySettings);
  });
}

const MainMenuLabels = {
  newScanDefinition: 'New Scan Definition...',
  deleteScanDefinition: 'Delete Scan Definition...',
  scan: 'Scan',
  scanAndMerge: 'Scan & Merge',
  replaceSource: 'Replace Source',
  replaceTarget: 'Replace Target',
  fileAttributes: 'View File Attributes...',
  viewScan: 'View Scan',
  viewHistory: 'View History',
  settings: 'Settings...',
};

app.whenReady().then(async () => {
  try {
    // Packaged builds spawn the bundled JRE + shaded jar copied into
    // <resources>/engine/ by forge.config.ts's packageAfterCopy hook.
    // Dev builds (yarn start) fall back to the launcher's mvn-layout default.
    const launchOpts: EngineLaunchOptions = app.isPackaged
      ? {
          bundledJrePath: path.join(process.resourcesPath, 'engine', 'jre'),
          bundledEngineJar: path.join(process.resourcesPath, 'engine', 'engine.jar'),
        }
      : {};
    startEngine(launchOpts);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error('[engine] Failed to start engine:', err);
    dialog.showErrorBox('Assurance: Engine startup failed', message);
    app.exit(1);
    return;
  }

  try {
    const ready = await whenEngineReady();
    console.log(`[engine] Ready on ${ready.url} (protocolVersion=${ready.protocolVersion}).`);
    const handshake = await engineClient.connect({
      url: ready.url,
      protocolVersion: IPC_PROTOCOL_VERSION,
      uiVersion: app.getVersion(),
    });
    console.log(
      `[engine] Connected. engineVersion=${handshake.engineVersion}, protocolVersion=${handshake.protocolVersion}.`,
    );
    engineClient.on('fatal', (fatal: EngineClientFatalError) => {
      console.error('[engine] Fatal IPC error:', fatal);
      dialog.showErrorBox(
        'Assurance: Engine connection lost',
        `${fatal.message}\n\nThe application will now close.`,
      );
      app.exit(1);
    });
    registerAppLifetimeIPC();
    setupMainMenu();
  } catch (err) {
    const fatal = err as EngineClientFatalError;
    const reason = fatal?.reason ?? 'unknown';
    const message = err instanceof Error ? err.message : String(err);
    console.error(`[engine] Engine handshake failed (${reason}):`, err);
    dialog.showErrorBox(
      'Assurance: Engine handshake failed',
      `${message}\n\nThe application cannot continue.`,
    );
    await stopEngine();
    app.exit(1);
    return;
  }

  createWindow();
});

let engineShutdownComplete = false;
app.on('before-quit', (event) => {
  if (engineShutdownComplete) {
    return;
  }
  event.preventDefault();
  if (teardownNotificationForwarders) {
    try {
      teardownNotificationForwarders();
    } catch (err) {
      console.warn('[ipc] Failed to detach engine notification forwarders:', err);
    }
    teardownNotificationForwarders = null;
  }
  try {
    engineClient.sendShutdownNotification();
  } catch (err) {
    console.warn('[engine] Failed to send shutdown notification:', err);
  }
  engineClient.close();
  stopEngine().finally(() => {
    engineShutdownComplete = true;
    app.quit();
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

